services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: node_starter
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: development
    container_name: node_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/node_starter
    ports:
      - "4000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  postgres_data: